version: '3.7'
services:

  src:
    container_name: spring_boot
    depends_on:
    - redis
    - mysql
    image: openjdk:11
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "./build/libs"
        target: "/app"
        read_only: true
    entrypoint: [ "java", "-jar", "/app/velo-chat-0.0.1-snapshot.jar" ]

  redis:
    container_name: spring_redis
    build: ./docker/redis
    ports:
      - "6379:6379"

# 결국 수동 구동하고 있기 때문에
# DB 구동시에 디비와 테이블을 구성해야 한다.
  mysql:
    container_name : spring_mysql
    image: library/mysql:latest
    build: ./docker/mysql
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - /Users/jmlim/datadir:/var/lib/mysql